In [6]:
import sys
import numpy as np

print('Python Version: {}'.format(sys.version))
print('Numpy: {}'.format(np.__version__))

Python Version: 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy: 1.16.2


In [7]:
# defining a scalar
x=6
x

6

In [14]:
# defining a vector
x = np.array((1,2,3))
x

array([1, 2, 3])

In [16]:
print('Vector Dimensions : {}'.format(x.shape))
print('Vector size: {}'.format(x.size))

Vector Dimensions : (3,)
Vector size: 3


In [17]:
# defining a matrix
x = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
print('Matrix dimensions: {}'.format(x.shape))
print('Matrix size: {}'.format(x.size))

Matrix dimensions: (3, 3)
Matrix size: 9


In [22]:
# defin a matrix of a given dimension
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
x = np.ones((3,3,3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
print('Tensor dimensions: {}'.format(x.shape))
print('Tensor size: {}'.format(x.size))

Tensor dimensions: (3, 3, 3)
Tensor size: 27


In [25]:
# indexing
A = np.ones((5,5), dtype=np.int)
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
# indexing starts at 0
A[0,1] = 2
A

array([[1, 2, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [28]:
# assigns all rows, column zero a valu
A[:,0] = 3
A

array([[3, 2, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1]])

In [29]:
# all rows and columns
A[:,:] = 5
A

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [30]:
# for higher dimensions simply add an index
A = np.ones((5,5,5),dtype= np.int)

#assign first row a new value
A[:,0,0] = 6
A

array([[[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [31]:
# matrix operations
A = np.matrix([[1,2],[3,4]])
B = np.ones((2,2),dtype=np.int)


In [32]:
A

matrix([[1, 2],
        [3, 4]])

In [33]:
B

array([[1, 1],
       [1, 1]])

In [34]:
# element wise addition
C = A + B
C

matrix([[2, 3],
        [4, 5]])

In [35]:
# element wise subtraction
C = A - B
C

matrix([[0, 1],
        [2, 3]])

In [36]:
# matrix mulitplication
C = A*B
C

matrix([[3, 3],
        [7, 7]])

In [37]:
# matrix transpose
A = np.array(range(9))
A = A.reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
B = A.T
B

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [39]:
C = B.T
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
A = np.array(range(10))
A = A.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
B = A.T
B

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [43]:
print(B.shape)
print(A.shape)

(5, 2)
(2, 5)


In [ ]:
# tensors
A =